name: Build Kivy App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk unzip git zip \
                              pkg-config libgl1-mesa-dev libgles2-mesa-dev \
                              build-essential ccache libffi-dev libssl-dev \
                              libsqlite3-dev libbz2-dev liblzma-dev \
                              python3-setuptools python3-wheel \
                              python3-cython python3-pil \
                              python3-kivy python3-dev

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install buildozer cython virtualenv

      - name: Create buildozer.spec if not exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Install Android SDK & NDK
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
          cd ~/.buildozer/android/platform/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          rm commandlinetools-linux-9477386_latest.zip
          mv cmdline-tools latest
          yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "cmdline-tools;latest" "ndk;21.4.7075529"

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-App-APK
          path: bin/*.apk
