name: Build APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/upload-artifact@v4


      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk unzip
          pip3 install --user --upgrade Cython virtualenv
          pip3 install --user buildozer
      
      - name: Install Android SDK & NDK
        run: |
          sudo apt install -y android-sdk android-sdk-platform-tools android-sdk-platform-33
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
          sdkmanager --install "build-tools;33.0.0" "platform-tools" "platforms;android-33" "ndk;25.1.8937393"
          sdkmanager --licenses || true

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MobileExpenseTracker
          path: bin/*.apk
