name: Build Kivy APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev \
        libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev
        pip3 install --user --upgrade cython virtualenv
        sudo apt-get install -y cython

    - name: Install Buildozer
      run: |
        git clone https://github.com/kivy/buildozer.git
        cd buildozer
        sudo python3 setup.py install
        cd ..

    - name: Initialize Buildozer (if needed)
      run: |
        if [ ! -f "buildozer.spec" ]; then
          buildozer init
        fi

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Kivy-APK
        path: bin/*.apk
