name: Build Kivy APK

on:
  push:
    branches:
      - master  # Runs the workflow when code is pushed to master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk

    - name: Install pip dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Install Android NDK & SDK
      run: |
        sudo apt install -y wget
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
        unzip android-ndk-r27c-linux.zip
        mv android-ndk-r27c $HOME/android-ndk
        echo "ANDROIDNDK=$HOME/android-ndk" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Kivy-App-APK
        path: bin/*.apk
