name: Build APK with Buildozer

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-11-jdk zip unzip cython3 libncurses6 libffi-dev libssl-dev

      - name: Install Buildozer and Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Install Android SDK, NDK, and Tools
        run: |
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/34.0.0:$PATH
          
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $ANDROID_HOME/cmdline-tools
          rm commandlinetools-linux-8512546_latest.zip

          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          yes | sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34" "ndk;25.2.9519653" "cmdline-tools;latest"

      - name: Initialize Buildozer Spec (If Missing)
        run: |
          if [ ! -f "buildozer.spec" ]; then
            buildozer init
          fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: bin/*.apk
